### ISSUE TITLE
Missing lookup table WordEmbed

### ISSUE THREAD

**Issue by rstrudel** [ChenyunWu/PhraseCutDataset#2]
Hi,

Thanks for open-sourcing the dataset. I want to use PhraseHandler and WordEmbed classes however I am missing the file `fast_text/lookup_refvg_all.npy` mentionned here:
https://github.com/ChenyunWu/PhraseCutDataset/blob/master/utils/word_embed.py#L5

Could you tell me how to download it ?

Thanks!

**Comment by ChenyunWu** [comment]
Hello,

Thanks for your interest in our work!

The file can be downloaded here:
https://umass-my.sharepoint.com/:u:/g/personal/chenyunwu_umass_edu/EQ67VX0xUq5OrwiD_UdLKnwBz3XZvNBSvLc2uhUgUPheDw?e=xA3gO4

It is simply the embeddings of our vocabulary from FastText "wiki-news-300d-1M.vec.zip” (link)

Best,
Chenyun

**Comment by rstrudel** [comment]
Hi,

Great, thank you for the link! Maybe I missed it but otherwise I think it could be good to include the file somewhere in the downloading script. I wanted a way to convert a short description to tokens and did not know how to do it until I found the WordEmbed class but could not use it because `fast_text/lookup_refvg_all.npy` was missing.

Best,

Robin
