### ISSUE TITLE
Request for model code of PhraseCut

### ISSUE THREAD

**Issue by tibetgao** [ChenyunWu/PhraseCutDataset#4]
Dear Chenyun,

Thanks for your great contribution on this amazing work.

I am wondering that if there is any official repo for the code from the paper (the url attached in the paper is currently not working).

Thanks for you time!

**Comment by ChenyunWu** [comment]
Thanks for your interest in our work!

Unfortunately, the model code repo is lost. I found a local copy of my code and uploaded it at https://drive.google.com/file/d/1TjJjbkqQjmL67bD449QZDTwM4ijSHTJE/view?usp=sharing

I hope it helps!

**Comment by ChenyunWu** [comment]
Closing the issue.

**Comment by msubhransu** [comment]
There is a foked copy at https://github.com/cvl-umass/PhraseCutDataset for
the dataset.

Best,
Subhransu
